# Generated by Django 5.1.15 on 2026-05-07 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('AGM', 'Annual General Meeting'), ('EGM', 'Extraordinary General Meeting'), ('DIV_EX', 'Ex-Dividend Date'), ('AR', 'Annual Report'), ('HY', 'Half-Year Result'), ('Q1', 'Q1 Result'), ('Q3', 'Q3 Result'), ('OTH_PROFIT_GUIDANCE', 'Profit Guidance'), ('OTH_TRADING_HALT', 'Trading Halt'), ('OTH_TRADING_RESUME', 'Resumption of Trading'), ('OTH_ACQ_DISPOSAL', 'Acquisition / Disposal'), ('OTH_AUDITOR_CHANGE', 'Auditor Change'), ('OTH_DIRECTOR_DEAL', 'Director / Substantial Shareholder Deal'), ('OTH_GENERAL', 'Other Material Announcement')], max_length=32)),
                ('view_category', models.CharField(choices=[('AGM_EGM', 'AGM/EGM'), ('DIVIDEND', 'Dividends'), ('REPORT', 'Reports'), ('OTHER', 'Other Announcements')], db_index=True, max_length=16)),
                ('event_date', models.DateField(db_index=True)),
                ('title', models.CharField(max_length=255)),
                ('sgx_announcement_url', models.URLField(blank=True)),
                ('company_ir_url', models.URLField(blank=True)),
                ('details_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='companies.company')),
            ],
            options={
                'ordering': ['event_date', 'company__ticker'],
                'indexes': [models.Index(fields=['view_category', 'event_date'], name='events_even_view_ca_8abd5e_idx')],
                'unique_together': {('company', 'event_type', 'event_date')},
            },
        ),
    ]
