# Generated by Django 5.1.15 on 2026-05-07 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('AGM', 'Annual General Meeting'), ('EGM', 'Extraordinary General Meeting'), ('DIV_EX', 'Ex-Dividend Date'), ('AR', 'Annual Report'), ('HY', 'Half-Year Result'), ('Q1', 'Q1 Result'), ('Q3', 'Q3 Result'), ('BIZ_UPDATE', 'Business Update'), ('OTH_PROFIT_GUIDANCE', 'Profit Guidance'), ('OTH_TRADING_HALT', 'Trading Halt'), ('OTH_TRADING_RESUME', 'Resumption of Trading'), ('OTH_ACQ_DISPOSAL', 'Acquisition / Disposal'), ('OTH_AUDITOR_CHANGE', 'Auditor Change'), ('OTH_DIRECTOR_DEAL', 'Director / Substantial Shareholder Deal'), ('OTH_GENERAL', 'Other Material Announcement')], max_length=32),
        ),
    ]
