# Generated by Django 5.1.15 on 2026-05-07 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=20, unique=True)),
                ('sgx_code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=64)),
                ('sector', models.CharField(blank=True, max_length=64)),
                ('listing_board', models.CharField(choices=[('Mainboard', 'Mainboard')], default='Mainboard', max_length=16)),
                ('investor_relations_url', models.URLField(blank=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['ticker'],
            },
        ),
    ]
