# Generated by Django 5.1.15 on 2026-05-17 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dailybar',
            new_name='prices_dail_company_cb9ab5_idx',
            old_name='prices_dail_company_b1aaff_idx',
        ),
        migrations.AlterField(
            model_name='dailybar',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
